### ISSUE TITLE
Wrong behavior using run example

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#1]
**Describe the bug**
executing the command:
dotnet run --framework netcoreapp3.1 JCOReflector\JCOReflectorCore.csproj
dotnet asks for --project flag.

**To Reproduce**
execute the commands in the sequence reported in the **_"How to use the generator tool (JCOReflector)"_** page

**Expected behavior**
That the command starts the application

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
The exact commands are the following one:

- dotnet run --framework netcoreapp3.1 --project JCOReflector\JCOReflectorCore.csproj
- dotnet run --framework net461 --project JCOReflector\JCOReflectorCore.csproj
