### ISSUE TITLE
Static properties in reflected classes are reflected as instance properties.

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#15]
**Describe the bug**
Static properties in reflected classes are reflected as instance properties.

**To Reproduce**
N/A

**Expected behavior**
Static properties should be reflected as static.

**Screenshots**
![image](https://user-images.githubusercontent.com/48452565/91655496-2b9c5c80-eab1-11ea-96bf-510fb0eb97b5.png)
In this screenshot is visible the effects of the bug.

**Desktop (please complete the following information):**
 - OS: Tested in Windows 10

**Additional context**
Reflected classes (**netreflected\src** folder)  in **commit f5b2a7a829b4774e3dac8b30a14a980a1869c826** show this problem.

**Comment by mariomastrodicasa** [comment]
I updated the reflector engine, the source code and documentation: this issue can be closed for me. @marcocappolimases verify and then close it.

**Comment by marcocappolimases** [comment]
Verified
