### ISSUE TITLE
Associate java.lang.AutoCloseable interface to system.IDisposable interface

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JCOReflector#16]
**Is your feature request related to a problem? Please describe.**
Classes that implements the **Disposable** interface in .NET are normally called with the using keyword. Reflected classes in java have not an equivalent paradigm to use. 

**Describe the solution you'd like**
Implementing the **[AutoClosable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html)** interface in reflected java classes is possible to emulate the **[using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)** behavior via the **[try-with-resource](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)** statement.  

**Describe alternatives you've considered**
No alternative was considered because it seams a 1 to 1 replacement for the **[using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)**.

**Additional context**
If StringReader implements the [AutoClosable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) interface, the following **c#** code 
```c#
using (StringReader reader = new StringReader(manyLines))
{
    do something with reader;
}
```
can be wrote in **java** as
```java
try (StringReader reader = new StringReader(manyLines)) {
       do something with reader;
 }
```

**Comment by mariomastrodicasa** [comment]
To simplify the implementation and avoid to add new templates (like the ones related to [IEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable) and [IEnumerator](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator)) I propose to:
- Create a new Java class named `NetObjectAutoCloseable` which:
  - `implements` [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html)
  - `extends` [NetObject](https://github.com/masesgroup/JCOReflector/blob/master/netreflected/src/JCOReflector/org/mases/jcobridge/netreflection/NetObject.java)
- During reflection, if the class under analysis implements [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable), use `NetObjectAutoCloseable` as base class instead to use [NetObject](https://github.com/masesgroup/JCOReflector/blob/master/netreflected/src/JCOReflector/org/mases/jcobridge/netreflection/NetObject.java)

The code stub of `NetObjectAutoCloseable` will be:

```java
public class NetObjectAutoCloseable extends NetObject implements AutoCloseable {

// other code

    public void close() throws Exception {
        try {
            if (classInstance == null)
                throw new UnsupportedOperationException("classInstance is null.");
            try {
                classInstance.Invoke("Dispose");
            } catch (JCNativeException jcne) {
                throw translateException(jcne);
            }
        } catch (Throwable t) {
            throw new java.lang.Exception(t);
        }
    }
}
```

**Comment by marcocappolimases** [comment]
In my opinion the proposed solution is a better solution than introducing a new template.

**Comment by mariomastrodicasa** [comment]
@marcocappolimases verify if the objects with [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) works as expected: we need to verify [try-with-resource](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) statement.

**Comment by marcocappolimases** [comment]
During the modification to the [HelloHierarchy.java](https://github.com/masesgroup/JCOReflector/blob/master/netreflected-tests/src/hierarchy/HelloHierarchy.java) test file to use the [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) statement, I discovered that Stream class doesn't implements [AutoClosable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) because of his Hierarchy.

**Comment by mariomastrodicasa** [comment]
> Checking better, the solution proposed in [#16 (comment)](https://github.com/masesgroup/JCOReflector/issues/16#issuecomment-685974931) does not cover all cases. The [Stream](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream) class implements [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface, but inherits from [MarshalByRefObject](https://docs.microsoft.com/en-us/dotnet/api/system.marshalbyrefobject). The implementation of the reflector engines expects the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface is at top-most hierarchy level. I think it is necessary to add a template in any case.

`NetObjectAutoCloseable` isn't enough to cover the cases, I will remove it and add, instead, an analyzer which adds the [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) interface in `implements` with the same `close` method use in `NetObjectAutoCloseable`.

**Comment by mariomastrodicasa** [comment]
> > Checking better, the solution proposed in [#16 (comment)](https://github.com/masesgroup/JCOReflector/issues/16#issuecomment-685974931) does not cover all cases. The [Stream](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream) class implements [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface, but inherits from [MarshalByRefObject](https://docs.microsoft.com/en-us/dotnet/api/system.marshalbyrefobject). The implementation of the reflector engines expects the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface is at top-most hierarchy level. I think it is necessary to add a template in any case.
> 
> `NetObjectAutoCloseable` isn't enough to cover the cases, I will remove it and add, instead, an analyzer which adds the [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) interface in `implements` with the same `close` method use in `NetObjectAutoCloseable`.

With commits https://github.com/masesgroup/JCOReflector/commit/db7334849194b942730ad5a97e81f140f637d98a and https://github.com/masesgroup/JCOReflector/commit/2c004c0eb4ab65b86fa079aeaf34025444d93a61 I added the reflected code containing the modification: @marcocappolimases  check if code now works with [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) statement.
