### ISSUE TITLE
Add the upcoming .NET 5 as target framework

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#19]
**Is your feature request related to a problem? Please describe.**
Microsoft is releasing .NET 5 as runtime framework, at the moment the framework version is not considered in the reflection process.

**Describe the solution you'd like**
Add .NET 5 as target framework

**Describe alternatives you've considered**
N/A

**Additional context**
Review the folder structure organization to add the new framework reflected classes.

**Comment by mariomastrodicasa** [comment]
As first stage, the folder names will be changed to be aligned to the ones used from the building system (e.g. net461, netcoreapp3.1).

**Comment by mariomastrodicasa** [comment]
@marcocappolimases I added reflection about .NET 5, we must add statistics related to this runtime (see #3)

**Comment by mariomastrodicasa** [comment]
@marcocappolimases during some smoke tests related to .NET 5.0 I discovered the deploy related to JCOBridge is not correct, it is important to contact JCOBridge team to know when it will be available for .NET 5.

**Comment by marcocappolimases** [comment]
No preliminary version of **JCOBridge** is planned before .NET 5 is released, but the **.NET Core runtime can be used in .NET 5** using a specific procedure.

**Comment by marcocappolimases** [comment]
> No preliminary version of **JCOBridge** is planned before .NET 5 is released, but the **.NET Core runtime can be used in .NET 5** using a specific procedure.

The procedure is described in the following **JCOBridge** forum [article](https://www.jcobridge.com/support/topic/support-net-5-prerelease-on-jcobridge/)

**Comment by mariomastrodicasa** [comment]
JCOBridge use .NET 5 as the default framework. JCOReflector does not manage the command-line arguments and it is not possible to send command-line arguments to JCOBridge. A new method shall be added to JCOBridgeInstance class to store command-line arguments before any operation is done from JCOReflector.
