### ISSUE TITLE
How to extend  .NET nuget package to be useful in java?

### ISSUE THREAD

**Issue by bopin2020** [masesgroup/JCOReflector#24]
I noticed there are serveral .net nuget package  assembly like(WindowsBase), but I needed to use dnlib this package in java, I researched your JCOReflector project,It's quitely awesome. I think you create a relative jar file after researching its .net assembly,
Right?  Here is dblib project: https://github.com/0xd4d/dnlib.  Nuget package: https://www.nuget.org/packages/dnlib/

I believe this project will be more popular in future, I even dont know how long do you spend for, I wanna say we are willing to donate you in order to make this project awesome. I really hope it could help more devlopers.

The next is to achieve external .net packages or assembly, it's not enough to basically needs or less than.

**Comment by mariomastrodicasa** [comment]
The project writes Java wrappers to interact with .NET and it is true: the latest step is to build JAR files to consume them in a JVM.
Any package comes with the JCOReflector executables: anyone can use the executables to "reflect" any external assembly into Java. So, for your specific purpose, you can use the packages, or clone the repository, and instruct JCOReflector to analyze the assembly dnlib.dll. The final output will be a dnlib.jar file.

About the title of the topic: it is possible to add a new feature to interact with NuGet servers and build Jar files from them.

Regarding sponsorship you are welcome, our consultants are analyzing fiscal documentation before adhere.

**Comment by mariomastrodicasa** [comment]
[NuReflector ](https://github.com/masesgroup/NuReflector) can help to solve this issue. Try to get a look and give us a feedback.
