### ISSUE TITLE
Replace reflection statistics with charts

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JCOReflector#3]
The idea is to have some charts instead of the text to describe the reflection coverage.

**Describe the solution you'd like**
Create some charts using the statistics captured during reflection process and put them into the readme.md file: any visitor can have a clear and concise vision of actual level.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
Seems that the column related to the **methods** highlights something is wrong.
Opened #4 to @marcocappolimases

**Comment by mariomastrodicasa** [comment]
**_Build classes_** and **_Create JARs_** processes delete the content of the statistics files.

**Comment by marcocappolimases** [comment]
Strictly spoken the fact is that various async tasks call the **EndOperationHandler** but only the task that elaborate the statistics call the **EndOperationEventArgs** constructor with 2 parameters. 

In my honest opinion a check is missed before the write of csv files.
The question is: to check only if it is null? 
Or is needed an **EndOperationEventArgs** property/flag to signal if the statistic elaboration process had a problem?
And in this case, what shall the **JCOReflector** do?

- Log the problem and skip the csv file update?
- Stop the elaboration and signal the problem?

**NB: Now in case of problem the message is directly wrote in the csv file instead of the data.**

**Comment by mariomastrodicasa** [comment]
I think the statistics can be write within the Reflector.cs without send them back to HMI before write file on disk. Surely this expects a change in the source destination folder received from HMI, as parameter, because now HMI send a value containing the "src" subfolder. If HMI send the root, the "src" subpath can be added from Reflector class and at the end of operations the reflector class can add "statistics" subpath to write the statistics if them are available.

Statistics file write can be avoided if some errors happens during the generation: this condition is reported in the report section of the HMI like in the previous version.

**Comment by marcocappolimases** [comment]
Ok, the new **source destination folder** will be one level up, this way it will be possible to add also other folders if needed, by now a new arg will be passed for the **statistics folder**.

**Comment by mariomastrodicasa** [comment]
Is it possible to add on the charts a percentage which measure the ratio between implemented and implementable methods?

**Comment by marcocappolimases** [comment]
Yes, this is possible and i'm working on it.

**Comment by mariomastrodicasa** [comment]
Seems good.

**Comment by mariomastrodicasa** [comment]
I discovered a wrong behavior while implementing issue #6. Seems that more than the available methods, properties and events are counted in the analyzed value. This conditions seems that comes from the fact that some methods, properties and events are counted multiple times due to inheritance (e.g. methods with override). We need to change the counting mechanism of analyzed methods, properties and events to have a better understanding of the real coverage. Upon the commit it is important to make a cross-check with .NET methods, properties and events availability. @marcocappolimases how we can do this cross-check?

**Comment by mariomastrodicasa** [comment]
@marcocappolimases please add statistics charts related to .NET 5
