### ISSUE TITLE
Upgrade to JCOBridge 2.4.* and .NET 6

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JCOReflector#61]
**Is your feature request related to a problem? Please describe.**
.NET 6 GA release is now available. JCOReflector shall be upgraded to the latest release.

**Describe the solution you'd like**
JCOReflector needs to accept .NET 6 as target framework, this implies to upgrade JCOBridge to the latest version.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
[Ubuntu ](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) does not support .NET until now. Complete rollout will be possible when .NET 6 will be available on Linux environment otherwise the projects shall be changed and based on the platform: if this approach is acceptable.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers we cannot diverge. Look at https://github.com/actions/virtual-environments/issues/4424 and, mainly, to https://github.com/actions/virtual-environments/issues/4424#issuecomment-964461088. We leave this issue open waiting for an update of the Linux machine.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers the website was not updated

**Comment by mariomastrodicasa** [comment]
@masesdevelopers you miss the .NET 6 version in the release file.

**Comment by mariomastrodicasa** [comment]
> @masesdevelopers you miss the .NET 6 version in the release.yaml file.

Missed update of Java VM in use

**Comment by mariomastrodicasa** [comment]
@masesdevelopers we have the problem of https://github.com/masesgroup/JCOReflector/issues/61#issuecomment-969069228

**Comment by mariomastrodicasa** [comment]
@masesdevelopers add this snippet to the project containing reference on JCOBridge to propagate management of .targets:
```
	<PackageReference Include="MASES.JCOBridge" Version="2.4.6">
		<IncludeAssets>All</IncludeAssets>
		<PrivateAssets>None</PrivateAssets>
	</PackageReference>
```
