### ISSUE TITLE
Java Documentation

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#7]
**Is your feature request related to a problem? Please describe.**
The generated java code lacks of documentation.

**Describe the solution you'd like**
Automatically create java documentation based on the .NET reflected classes documentation.

**Describe alternatives you've considered**
- Auto generated documentation for methods and parameters.
- Links to .NET documentation.

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
@marcocappolimases as first stage I think we can add a link to the Microsft documentation like the following one:

https://docs.microsoft.com/en-us/dotnet/api/**{fulltypename}**

It has a common pattern and it is valid for both .NET Framework and .NET Core. An extended specification is the following one:

https://docs.microsoft.com/en-us/dotnet/api/**{fulltypename}**?view=netframework-4.6.1
https://docs.microsoft.com/en-us/dotnet/api/**{fulltypename}**?view=netcore-3.1

Examples are like the following one:

https://docs.microsoft.com/en-us/dotnet/api/system.type?view=netframework-4.6.1
https://docs.microsoft.com/en-us/dotnet/api/system.type?view=netcore-3.1

On the template header, beside the fullname of the implemented type, it is possible to add the link as in the following snippet:

``` 
/**
 * The base .NET class managing FULLYQUALIFIED_CLASS_NAME, FULL_ASSEMBLY_CLASS_NAME. Extends {@link NetObject}.
 * <p>
 * @see https://docs.microsoft.com/en-us/dotnet/api/FULLYQUALIFIED_CLASS_NAME
 */
```

**Comment by mariomastrodicasa** [comment]
@marcocappolimases what do you think if we create another folder, named **docs**, at the same level of **src** and **statistics**?
Below docs we can divide documentation between **Framework** and **Core**.

**Comment by marcocappolimases** [comment]
In my opinion is the better solution. 
This solution respects the actual folders structure and is scalable.
What about linking the doc folder at the same level of **src** and **statistics** to a **doc** folder in the root of repository?

**Comment by mariomastrodicasa** [comment]
Do you mean to create a **docs** folder at root level as requested from github-pages? I think it can be done using symlinks...

**Comment by mariomastrodicasa** [comment]
For a better navigation experience, it is important to add the references to the [root of the repository](https://masesgroup.github.io/JCOReflector) and a reference to [JCOBridge](https://www.jcobridge.com). @marcocappolimases, using the javadoc option `-header`, I will put in the header of the generated doc the following snippet:
```HTML
<a href="https://masesgroup.github.io/JCOReflector" style="text-decoration: none;margin-left: 0;padding: 1px 20px 0 0;font-size: 60px;font-weight: 200;color: #777777;text-shadow: 0 1px 0 #ffffff;"><b>JCOReflector</b></a> powered by </large><a href="https://www.jcobridge.com/" style="text-decoration: none;overflow: hidden;margin-left: 0;padding: 1px 20px 0 0;font-size: 60px;font-weight: 200;color: #777777;text-shadow: 0 1px 0 #ffffff;"><span style="color: #5090FF;"> <img src="https://www.jcobridge.com/LogoSquare.png" width="45">J<small>VM CLR Objects Bridge</small></span></a>
```
will be rendered as:

![image](https://user-images.githubusercontent.com/48451703/89711596-8dbee180-d98b-11ea-8a0b-3002c8ef0ab0.png)

**Comment by mariomastrodicasa** [comment]
The documentation reports all *Implementation.java classes. These classes are internal and cannot be used by developer, so we must remove them from the generated docs.

**Comment by mariomastrodicasa** [comment]
Generating documentation it is reported that `@param` and `@return` are missing on `cast` operation, this tags will be added into templates to avoid warning.

**Comment by mariomastrodicasa** [comment]
Some class descriptions reports wrong class names like the following one.

```java
/**
 * The base .NET class managing FULLYQUALIFIED_CLASS_NAME, FULL_ASSEMBLY_CLASS_NAME. Extends {@link NetObject}.
 * <p>
 * 
 * See: <a href="https://docs.microsoft.com/en-us/dotnet/api/FULLYQUALIFIED_CLASS_NAME" target="_top">https://docs.microsoft.com/en-us/dotnet/api/FULLYQUALIFIED_CLASS_NAME</a>
 */
```
shall be
```java
/**
 * The base .NET class managing FULLYQUALIFIED_CLASS_NAME, FULL_ASSEMBLY_CLASS_NAME. Extends {@link PACKAGE_CLASS_BASE_CLASS}.
 * <p>
 * 
 * See: <a href="https://docs.microsoft.com/en-us/dotnet/api/FULLYQUALIFIED_CLASS_NAME" target="_top">https://docs.microsoft.com/en-us/dotnet/api/FULLYQUALIFIED_CLASS_NAME</a>
 */
```
