### ISSUE TITLE
Wrong behavior of pullrequests.yaml and linux.yaml

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JCOReflector#87]
**Describe the bug**
Looking at #85 the check was not performed, and https://github.com/masesgroup/JCOReflector/actions/runs/1963318895 reports to runs in Trial mode.

**Expected behavior**
- **pullrequests.yaml** shall be executed and shall be valid before a merge into main repository;
- **linux.yaml** shall do not run in trial mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GitHub workflows host runner
 - Version: 1.9.0

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
For security reason pullrequest does not have rights to access secrets, there are two options: remove the tests or execute them without the license.

Linux workflow must be checked to verify if the file is written in the right location.

**Comment by masesdevelopers** [comment]
> For security reason pullrequest does not have rights to access secrets, there are two options: remove the tests or execute them without the license.
> 
> Linux workflow must be checked to verify if the file is written in the right location.

About pullrequests.yaml the idea is compile everything, but avoid execution of the tests
