### ISSUE TITLE
Add Out and Ref parameters

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#9]
**Is your feature request related to a problem? Please describe.**
Some classes in .NET use the **out** and **ref** keyword in their methods. It can be useful to have something like this in Java. An example are the methods **TryParse** that avoids the use of _try...catch_ blocks when the **Parse** function is used.

**Describe the solution you'd like**
A method in Java whose name and behavior reflects the one in .NET.

**Describe alternatives you've considered**
No alternative since Java lacks on this features.

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
As stated Java lacks on a feature like the expected ones. In C# **ref** and **out** can be applied to native types, structs and classes. In Java it is possible to use the set of types in the package _java.util.concurrent.atomic_ (e.g. [AtomicInteger](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/atomic/AtomicInteger.html)). Actually the reflector is not ready to automatically maps the types found during reflection in something that can be used within Java.

A possible solution is to create a method, or use the same code inline, with a snippet like the following one:

```Java
AtomicLong longVal = new AtomicLong(3L);
JCRefOut jcr = JCRefOut.Create(longVal);

if (!(boolean) UInt64.classType.Invoke("TryParse", "4", jcr)) {
 // FAILED
}

```

The example above does not work because the method on .NET side expects an unsigned type while the Java type is a signed type; the snippet is only a sample to show how it is possible to avoid the missing feature. But what is evident is the use of _java.util.concurrent.atomic.*_, with [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) and [JCType](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCType.html).

Looking in the repo I notice there are missing types can be useful: there are the usigned types and not the signed one, because the reflector maps them in the Java native types. I think can be useful to add them in JCOReflector common Java classes.

**Comment by mariomastrodicasa** [comment]
As stated in https://github.com/masesgroup/JCOReflector/issues/9#issuecomment-652557460 is it possible to use [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) to incapsulate an object in a function which needs both **ref** or **out** keywords.
JCOReflector introduced JCORefOut to handle conditions where native arrays are used in a function to return back data from .NET invocation.

One possible solution to handle **ref** or **out** in the methods can be the following. Consider the example signature below:
```c#
void Method(out MyClass obj);
```
using an evolved version of JCORefOut in _Java_ it becomes:
```java
void Method(JCORefOut<MyClass> objRef);
```
where _objRef_ will be created using `JCORefOut<MyClass>.Create(MyClass obj)`.
In JCORefOut we need to manage the condition where the input is a class: this implies to intercept in https://github.com/masesgroup/JCOReflector/blob/10b254543f6abd3b9ecb95ad2b3be8105afa524f/netreflected/src/JCOReflector/org/mases/jcobridge/netreflection/JCORefOut.java#L78 that the input is a reflected object and use https://github.com/masesgroup/JCOReflector/blob/10b254543f6abd3b9ecb95ad2b3be8105afa524f/netreflected/src/JCOReflector/org/mases/jcobridge/netreflection/IJCOBridgeReflected.java#L61 to retrieve the undelying .NET real object. A possible update to the class can be the following:
```java
    /**
     * Returns an instance of {@link JCRefOut} to be passed to the underlying layer
     * 
     * @return an instance of {@link JCRefOut}
     */
    public Object getJCRefOut() throws Throwable {
        if (mrefObj != null) {
            if (mrefObj instanceof IJCOBridgeReflected) {
                IJCOBridgeReflected o = (IJCOBridgeReflected) mrefObj;
                return JCRefOut.Create(o.getJCOInstance());
            } else
                return JCRefOut.Create((T) mrefObj);
        } else {
            if (mrefArray != null && mrefArray.length > 0 && mrefArray[0] instanceof IJCOBridgeReflected) {
                ArrayList<Object> retValJCArrayList = new ArrayList<Object>();
                for (int index = 0; index < mrefArray.length; index++) {
                    IJCOBridgeReflected o = (IJCOBridgeReflected) mrefArray[index];
                    retValJCArrayList.add(o.getJCOInstance());
                }
                return JCRefOut.Create(retValJCArrayList.toArray());
            } else
                return JCRefOut.Create((T[]) mrefArray);
        }
    }
```

**Comment by mariomastrodicasa** [comment]
The workflow run https://github.com/mariomastrodicasa/JCOReflector/actions/runs/1091988727 reports, for all involved frameworks, the error _have the same erasure, yet neither hides the other_ on method **TryParse**  in the following class couples:
- [MediaTypeWithQualityHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.mediatypewithqualityheadervalue) and [MediaTypeWithQualityHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.mediatypeheadervalue)
- [NameValueWithParametersHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.namevaluewithparametersheadervalue) and [NameValueHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.namevalueheadervalue)
- [TransferCodingWithQualityHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.transfercodingwithqualityheadervalue) and [TransferCodingHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.transfercodingheadervalue)

The problem can raise from the class hierarchy: the method **TryParse** has a different signature in all classes, but the type used with **JCORefOut** follows the same hierarchy of the membership class. Even if it is possible to identify this condition, in my opinion it is enough to check, only if RefOut option is enabled, the type and method to avoid code generation of **TryParse** for [MediaTypeWithQualityHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.mediatypewithqualityheadervalue), [NameValueWithParametersHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.namevaluewithparametersheadervalue) and [TransferCodingWithQualityHeaderValue](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.transfercodingwithqualityheadervalue).
